name: bloc_demo
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  bottom_bar_matu: ^1.5.0

#  LocalDatabase
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

#  Latlong get
  geolocator: ^14.0.1

#  Notification use
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/svg/